#!/usr/bin/env python3
"""
Converts the plain CSV/JSON data files in data/ into the JSON files the site
actually reads (modules/roster/*.json, modules/calendar/events.json, and
modules/sop/sop.json).

Why this exists: nobody should have to hand-edit JSON to update the roster
or calendar. Instead, fill in the CSV templates in data/ (Excel or Google
Sheets can save directly to CSV) and this script -- run automatically by
.github/workflows/sync-data.yml whenever those CSVs change -- regenerates
the JSON the site serves.

Run locally with:  python3 scripts/build_data.py
Exits non-zero with a clear message if a CSV is malformed, so a bad edit
gets caught before it reaches the live site.
"""

import csv
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]


class DataError(Exception):
    pass


def read_csv_rows(path):
    if not path.exists():
        raise DataError(f"Missing required file: {path.relative_to(ROOT)}")
    with path.open(newline="", encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise DataError(f"{path.relative_to(ROOT)} has no data rows.")
    return rows


def _read_roster_rooms():
    """Parses data/roster.csv into (floors_order, floors_map) -- shared by
    build_roster() and build_beautification() so the room list has exactly
    one source of truth."""
    rows = read_csv_rows(DATA / "roster.csv")
    floors_order = []
    floors_map = {}
    seen_rooms = set()

    for i, row in enumerate(rows, start=2):  # row 1 is the header
        room = (row.get("room") or "").strip()
        floor = (row.get("floor") or "").strip()
        if not room or not floor:
            raise DataError(
                f"data/roster.csv line {i}: both 'room' and 'floor' are required."
            )
        if room in seen_rooms:
            raise DataError(f"data/roster.csv line {i}: room '{room}' is listed more than once.")
        seen_rooms.add(room)

        if floor not in floors_map:
            floors_map[floor] = []
            floors_order.append(floor)
        floors_map[floor].append(room)

    return floors_order, floors_map


def build_roster():
    config_path = DATA / "roster-config.json"
    if not config_path.exists():
        raise DataError(f"Missing required file: {config_path.relative_to(ROOT)}")
    config = json.loads(config_path.read_text(encoding="utf-8"))

    rotation_start = config.get("rotationStart")
    if not rotation_start or not DATE_RE.match(rotation_start):
        raise DataError(
            "data/roster-config.json: 'rotationStart' must be a YYYY-MM-DD date."
        )

    floors_order, floors_map = _read_roster_rooms()

    rooms_json = {
        "_comment": (
            "Generated by scripts/build_data.py from data/roster.csv and "
            "data/roster-config.json -- do not edit this file directly, "
            "your changes will be overwritten on the next sync. Edit the "
            "CSV/config instead."
        ),
        "rotationStart": rotation_start,
        "floors": [
            {"name": floor, "rooms": floors_map[floor]} for floor in floors_order
        ],
    }
    return rooms_json


def build_roster_tasks():
    rows = read_csv_rows(DATA / "roster-tasks.csv")
    tasks_map = {day: [] for day in WEEKDAYS}

    for i, row in enumerate(rows, start=2):
        weekday = (row.get("weekday") or "").strip()
        task = (row.get("task") or "").strip()
        if weekday not in tasks_map:
            raise DataError(
                f"data/roster-tasks.csv line {i}: 'weekday' must be one of "
                f"{', '.join(WEEKDAYS)} (got '{weekday}')."
            )
        if not task:
            raise DataError(f"data/roster-tasks.csv line {i}: 'task' is required.")
        tasks_map[weekday].append(task)

    for day in WEEKDAYS:
        if not tasks_map[day]:
            raise DataError(f"data/roster-tasks.csv: no tasks listed for {day}.")

    return {
        "_comment": (
            "Generated by scripts/build_data.py from data/roster-tasks.csv -- "
            "edit that file, not this one."
        ),
        "tasks": tasks_map,
    }


def build_roster_notes():
    path = DATA / "roster-notes.json"
    if not path.exists():
        raise DataError(f"Missing required file: {path.relative_to(ROOT)}")
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise DataError(f"data/roster-notes.json is not valid JSON: {e}")

    notes = config.get("notes")
    if not isinstance(notes, list) or not notes:
        raise DataError("data/roster-notes.json: 'notes' must be a non-empty list of strings.")
    for i, note in enumerate(notes):
        if not isinstance(note, str) or not note.strip():
            raise DataError(f"data/roster-notes.json: notes[{i}] must be a non-empty string.")

    return {
        "_comment": (
            "Generated by scripts/build_data.py from data/roster-notes.json -- "
            "edit that file, not this one."
        ),
        "notes": [n.strip() for n in notes],
    }


TIME_RE = re.compile(r"^([01]\d|2[0-3]):([0-5]\d)$")


def build_beautification():
    path = DATA / "beautification-config.json"
    if not path.exists():
        raise DataError(f"Missing required file: {path.relative_to(ROOT)}")
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise DataError(f"data/beautification-config.json is not valid JSON: {e}")

    anchor_date = config.get("anchorDate")
    if not anchor_date or not DATE_RE.match(anchor_date):
        raise DataError("data/beautification-config.json: 'anchorDate' must be a YYYY-MM-DD date.")

    start_time = config.get("startTime")
    if not start_time or not TIME_RE.match(start_time):
        raise DataError("data/beautification-config.json: 'startTime' must be 24-hour HH:MM.")

    interval_days = config.get("intervalDays")
    if not isinstance(interval_days, int) or interval_days < 1:
        raise DataError("data/beautification-config.json: 'intervalDays' must be a positive integer.")

    rooms_per_draw = config.get("roomsPerDraw")
    if not isinstance(rooms_per_draw, int) or rooms_per_draw < 1:
        raise DataError("data/beautification-config.json: 'roomsPerDraw' must be a positive integer.")

    _, floors_map = _read_roster_rooms()
    all_rooms = [room for floor_rooms in floors_map.values() for room in floor_rooms]

    if rooms_per_draw > len(all_rooms):
        raise DataError(
            f"data/beautification-config.json: 'roomsPerDraw' ({rooms_per_draw}) can't be "
            f"more than the total number of rooms in data/roster.csv ({len(all_rooms)})."
        )

    return {
        "_comment": (
            "Generated by scripts/build_data.py from data/beautification-config.json "
            "and data/roster.csv (for the room pool) -- edit those, not this one."
        ),
        "anchorDate": anchor_date,
        "startTime": start_time,
        "intervalDays": interval_days,
        "roomsPerDraw": rooms_per_draw,
        "rooms": all_rooms,
    }


def _validate_sop_node(node, path, seen_ids):
    if not isinstance(node, dict):
        raise DataError(f"data/sop-content.json: {path} must be an object.")
    node_id = node.get("id")
    if not node_id or not isinstance(node_id, str):
        raise DataError(f"data/sop-content.json: {path} is missing a non-empty 'id'.")
    if node_id in seen_ids:
        raise DataError(f"data/sop-content.json: duplicate id '{node_id}' (ids must be unique across the whole document -- they're used as page anchors).")
    seen_ids.add(node_id)

    heading = node.get("heading")
    if not heading or not isinstance(heading, str):
        raise DataError(f"data/sop-content.json: {path} (id '{node_id}') is missing a non-empty 'heading'.")

    text = node.get("text")
    items = node.get("items")
    children = node.get("children")
    if text is not None and not isinstance(text, str):
        raise DataError(f"data/sop-content.json: {path} (id '{node_id}') 'text' must be a string.")
    if items is not None:
        if not isinstance(items, list) or not all(isinstance(i, str) and i.strip() for i in items):
            raise DataError(f"data/sop-content.json: {path} (id '{node_id}') 'items' must be a list of non-empty strings.")
    if children is not None:
        if not isinstance(children, list):
            raise DataError(f"data/sop-content.json: {path} (id '{node_id}') 'children' must be a list.")
        for i, child in enumerate(children):
            _validate_sop_node(child, f"{path} > children[{i}]", seen_ids)

    if not text and not items and not children:
        raise DataError(f"data/sop-content.json: {path} (id '{node_id}') needs at least one of 'text', 'items', or 'children'.")


def build_sop():
    path = DATA / "sop-content.json"
    if not path.exists():
        raise DataError(f"Missing required file: {path.relative_to(ROOT)}")
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise DataError(f"data/sop-content.json is not valid JSON: {e}")

    if not config.get("title"):
        raise DataError("data/sop-content.json: 'title' is required.")
    sections = config.get("sections")
    if not isinstance(sections, list) or not sections:
        raise DataError("data/sop-content.json: 'sections' must be a non-empty list.")

    seen_ids = set()
    for i, section in enumerate(sections):
        _validate_sop_node(section, f"sections[{i}]", seen_ids)

    buildings = config.get("buildings")
    if buildings is not None:
        if not isinstance(buildings, dict):
            raise DataError("data/sop-content.json: 'buildings' must be an object.")
        blist = buildings.get("list")
        if not isinstance(blist, list) or not blist:
            raise DataError("data/sop-content.json: 'buildings.list' must be a non-empty list.")
        seen_buildings = set()
        for i, b in enumerate(blist):
            if not isinstance(b, dict) or not b.get("building") or not b.get("unit") or not b.get("placardImage"):
                raise DataError(f"data/sop-content.json: buildings.list[{i}] needs 'building', 'unit', and 'placardImage'.")
            if b["building"] in seen_buildings:
                raise DataError(f"data/sop-content.json: building '{b['building']}' is listed more than once.")
            seen_buildings.add(b["building"])

    return {
        "_comment": (
            "Generated by scripts/build_data.py from data/sop-content.json -- "
            "edit that file, not this one."
        ),
        "title": config["title"],
        "sourceDoc": config.get("sourceDoc", ""),
        "references": config.get("references", []),
        "sections": sections,
        "buildings": buildings,
    }


def build_events():
    rows = read_csv_rows(DATA / "events.csv")
    events = []
    for i, row in enumerate(rows, start=2):
        date = (row.get("date") or "").strip()
        title = (row.get("title") or "").strip()
        description = (row.get("description") or "").strip()
        event_type = (row.get("type") or "other").strip() or "other"

        if not date or not DATE_RE.match(date):
            raise DataError(
                f"data/events.csv line {i}: 'date' must be a YYYY-MM-DD date, got '{date}'."
            )
        if not title:
            raise DataError(f"data/events.csv line {i}: 'title' is required.")

        events.append(
            {"date": date, "title": title, "description": description, "type": event_type}
        )

    events.sort(key=lambda e: e["date"])
    return events


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    text = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    path.write_text(text, encoding="utf-8")
    print(f"Wrote {path.relative_to(ROOT)}")


def main():
    try:
        rooms_json = build_roster()
        tasks_json = build_roster_tasks()
        notes_json = build_roster_notes()
        events_json = build_events()
        sop_json = build_sop()
        beautification_json = build_beautification()
    except DataError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    write_json(ROOT / "modules" / "roster" / "rooms.json", rooms_json)
    write_json(ROOT / "modules" / "roster" / "tasks.json", tasks_json)
    write_json(ROOT / "modules" / "roster" / "notes.json", notes_json)
    write_json(ROOT / "modules" / "calendar" / "events.json", events_json)
    write_json(ROOT / "modules" / "sop" / "sop.json", sop_json)
    write_json(ROOT / "modules" / "beautification" / "config.json", beautification_json)


if __name__ == "__main__":
    main()
